development:
  adapter: postgresql
  encoding: unicode
  database: sandalz_development
  pool: 5
  username: sandalz_dev
  password: sandalz_dev

test:
  adapter: postgresql
  encoding: unicode
  database: sandalz_test
  pool: 5
  username: sandalz_test
  password: sandalz_test

production:
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5
  username: 
  password: