development:
  adapter: postgresql
  encoding: unicode
  database: sandalz_development
  host: localhost
  pool: 5
  username: sandalz_dev
  password: sandalz_dev

test:
  adapter: postgresql
  encoding: unicode
  database: sandalz_test
  host: localhost
  pool: 5
  username: sandalz_dev
  password: sandalz_dev

production:
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5
  username:
   password: